# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 16afaab2049a06a420a8124b14c2e6c9da9bb954b6953addf1894395db559018d0c6ed372c401b8a86cbb7f33d34df8d61b8898be232ff2fcd80525917753148

test:
  secret_key_base: 10b476e96a1f137a14e205e3bb398f88201318b55e406c4041d5ed2b60a63d8646d362485353f7358dc8f61c835c8bc5f7a7f8973e08cffa38b947b6aa31aeed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
